# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/solid': '@latest-kf6'
    'frameworks/kauth': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/plasma-framework': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/networkmanager-qt': '@latest-kf6'
    'frameworks/modemmanager-qt': '@latest-kf6'
    'libraries/kirigami-addons': '@latest-kf6'
