# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/solid': '@stable'
    'frameworks/kauth': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/kdeclarative': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/networkmanager-qt': '@stable'
    'frameworks/modemmanager-qt': '@stable'
    'plasma/plasma-framework': 'kf5'
    'libraries/kirigami-addons': '@latest'
